<%@ Page Title="" Language="C#" MasterPageFile="AdminMasterPage.master" AutoEventWireup="true" CodeFile="Contactdetail.aspx.cs" Inherits="Admin_Contactdetail" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
      <style>
        /* Style for container */
        .container {
            margin-top: 20px;
        }

        /* Style for gridview */
        #GridView1 {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 14px;
        }

        /* Style for gridview header */
        #GridView1 th {
            background-color: #f2f2f2;
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        /* Style for gridview rows */
        #GridView1 td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        /* Style for alternating gridview rows */
        #GridView1 tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Style for image column */
        .room-image {
            width: 150px;
            height: 150px;
            object-fit: cover;
        }

    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

     <center style="margin-top:50px">
        <h1>View Contact Details</h1>
    </center>
    <div class="container" >
        <div style="text-align:center;overflow:scroll; width:90%; ">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" OnRowDataBound="GridView1_RowDataBound" DataKeyNames="conid" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <Columns>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("conid") %>' Width="70px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    
                 <%--   <asp:TemplateField HeaderText="Blog Image">
                        <ItemTemplate>
                            <asp:Image ID="Image1" class="clickable-image" runat="server" ImageUrl='<%# Eval("blogimg","Blogimg/{0}") %>' CssClass="room-image"/>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:FileUpload ID="FileUpload1" runat="server" />
                        </EditItemTemplate>
                    </asp:TemplateField>--%>

                    <asp:TemplateField HeaderText="Status">
                     <ItemTemplate>
                        <asp:Label ID="LabelStatus" runat="server" Text='<%# Eval("status") %>' Width="120px"></asp:Label>
                     </ItemTemplate>

                     <EditItemTemplate>
                         <asp:DropDownList ID="ddlStatus" runat="server">
                             <asp:ListItem Text="Not Verified" Value="Not Verified"></asp:ListItem>
                            <asp:ListItem Text="Verified" Value="Verified"></asp:ListItem>
                            
                         </asp:DropDownList>
                      </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Con. Name">
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Eval("conname") %>' Width="120px"></asp:Label>
                        </ItemTemplate>

                      <%--  <EditItemTemplate>
                            <asp:TextBox ID="upbname" runat="server"  Text='<%# Eval("conname") %>' Width="120px"></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField> 

                    <asp:TemplateField HeaderText="Email">
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Eval("conemail") %>' Width="250px"></asp:Label>
                        </ItemTemplate>

<%--                        <EditItemTemplate>
                            <asp:TextBox ID="upbtitle" runat="server"  Text='<%# Eval("conemail") %>' Width="120px"></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField> 
                    
                     
                    <asp:TemplateField HeaderText="Contact..">
                        <ItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Eval("conphone") %>' Width="120px"></asp:Label>
                        </ItemTemplate>

                       <%-- <EditItemTemplate>
                            <asp:TextBox ID="upbdesc" runat="server" Text='<%# Eval("conphone") %>'></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField>  
                    
                    <asp:TemplateField HeaderText="message..">
                        <ItemTemplate>
                            <asp:Label ID="Label7" runat="server" Text='<%# Eval("conmsg") %>' Width="120px"></asp:Label>
                        </ItemTemplate>

                       <%-- <EditItemTemplate>
                            <asp:TextBox ID="upbdesc" runat="server" Text='<%# Eval("conphone") %>'></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField>
                        
                    <asp:TemplateField HeaderText="Date">
                        <ItemTemplate>
                            <asp:Label ID="Label8" runat="server" Text='<%# Eval("condate") %>' Width="110px"></asp:Label>
                        </ItemTemplate>
                       <%-- <EditItemTemplate>
                            <asp:TextBox ID="upbdate" TextMode="Date" runat="server" Text='<%# Eval("condate") %>'></asp:TextBox>
                        </EditItemTemplate>--%>
                    </asp:TemplateField>

                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        </div>
    </div>

</asp:Content>

