<%@ Page Title="" Language="C#" MasterPageFile="AdminMasterPage.master" AutoEventWireup="true" CodeFile="Roomdetail.aspx.cs" Inherits="Admin_Roomdetail" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style>
        /* Style for container */
        .container {
            margin-top: 20px;
        }

        /* Style for gridview */
        #GridView1 {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 14px;
        }

        /* Style for gridview header */
        #GridView1 th {
            background-color: #f2f2f2;
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        /* Style for gridview rows */
        #GridView1 td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        /* Style for alternating gridview rows */
        #GridView1 tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Style for image column */
        .room-image {
            width: 150px;
            height: 150px;
            object-fit: cover;
        }

    </style>

    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <center style="margin-top:50px">
        <h1>View Room Details</h1>
    </center>
    <div class="container" style="overflow:scroll; width:90%; height:550px; ">
        <div style="text-align:center">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Roomid" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDataBound="GridView1_RowDataBound" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" >
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <Columns>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("Roomid") %>' Width="70px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    
                   <%-- <asp:TemplateField HeaderText="Booking Status">
                        <ItemTemplate>
                            <asp:Label ID="lblbs" runat="server" Text='<%# Eval("bookingstatus") %>' Width="130px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>--%>
                    
                    <asp:TemplateField HeaderText="Room Image">
                        <ItemTemplate>
                            <asp:Image ID="Image1" class="clickable-image" runat="server" ImageUrl='<%# Eval("room_image","Roomimg/{0}") %>' CssClass="room-image"/>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:FileUpload ID="FileUpload1" runat="server" />
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Room No..">
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Eval("rnum") %>' Width="120px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="uprnum" runat="server"  Text='<%# Eval("rnum") %>' Width="120px"></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField> 

                    <asp:TemplateField HeaderText="Room Price">
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Eval("rprice") %>' Width="110px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="uprprice" runat="server"  Text='<%# Eval("rprice") %>' Width="120px"></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField> 
                    
                    <asp:TemplateField HeaderText="Room Type">
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Eval("rtype") %>' Width="110px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:DropDownList ID="ddluprtype" runat="server" CssClass="form-control" Width="150px">
                                <asp:ListItem> --Select Room Type</asp:ListItem>
                                <asp:ListItem>AC Single</asp:ListItem>
                                <asp:ListItem>AC Double</asp:ListItem>
                                <asp:ListItem>NON-AC</asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    
                    <asp:TemplateField HeaderText="Bed Type">
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Eval("bedtype") %>' Width="110px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                             <asp:DropDownList ID="ddlupbedtype" runat="server" CssClass="form-control" Width="150px">
                                <asp:ListItem>--Select Bed Type</asp:ListItem>
                                    <asp:ListItem>Single Bed</asp:ListItem>
                                    <asp:ListItem>Double Bed</asp:ListItem>
                             </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    
                    <asp:TemplateField HeaderText="Room Catg..">
                        <ItemTemplate>
                            <asp:Label ID="Label5" runat="server" Text='<%# Eval("rcatg") %>' Width="110px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:DropDownList ID="ddluprcatg" runat="server" CssClass="form-control" Width="150px">
                                <asp:ListItem>--Select Room Category</asp:ListItem>
                                <asp:ListItem>Delux</asp:ListItem>
                                  <asp:ListItem>Super Delux</asp:ListItem>
            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                     
                    <asp:TemplateField HeaderText="Room Desc..">
                        <ItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Eval("rdesc") %>' Width="110px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="uprdesc" runat="server" Text='<%# Eval("rdesc") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                        
                    <asp:TemplateField HeaderText="Date">
                        <ItemTemplate>
                            <asp:Label ID="Label7" runat="server" Text='<%# Eval("rdate") %>' Width="110px"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="uprdate" TextMode="Date" runat="server" Text='<%# Eval("rdate") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

            <%--<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Roomid">
                <Columns>

                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("Roomid") %>' Width="70px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>


                    <asp:TemplateField HeaderText="Booking Status">
                        <ItemTemplate>
                            <asp:Label ID="lblbs" runat="server" Text='<%# Eval("bookingstatus") %>' Width="130px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Room Image">
                        <ItemTemplate>
                            <asp:Image ID="Image1" class="clickable-image" runat="server" ImageUrl='<%# Eval("room_image","Roomimg/{0}") %>' CssClass="room-image"/>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:FileUpload ID="FileUpload1" runat="server" />
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Room No..">
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Eval("rnum") %>' Width="120px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="uprnum" runat="server"  Text='<%# Eval("rnum") %>' Width="120px"></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>--%>
        </div>
    </div>
</asp:Content>
