<%@ Page Title="" Language="C#" MasterPageFile="AdminMasterPage.master" AutoEventWireup="true" CodeFile="Servicedetail.aspx.cs" Inherits="Admin_Servicedetail" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
     <style>
        /* Style for container */
        .container {
            margin-top: 20px;
        }

        /* Style for gridview */
        #GridView1 {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 14px;
        }

        /* Style for gridview header */
        #GridView1 th {
            background-color: #f2f2f2;
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        /* Style for gridview rows */
        #GridView1 td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        /* Style for alternating gridview rows */
        #GridView1 tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Style for image column */
        .room-image {
            width: 150px;
            height: 150px;
            object-fit: cover;
        }

    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

     <center style="margin-top:50px">
        <h1>View Room Details</h1>
    </center>
    <div class="container" style="overflow:scroll; width:90%; height:550px; ">
        <div style="text-align:center">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="serviceid" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" >
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <Columns>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("serviceid") %>' Width="70px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    
                    <asp:TemplateField HeaderText="Sevice Image">
                        <ItemTemplate>
                            <asp:Image ID="Image1" class="clickable-image" runat="server" ImageUrl='<%# Eval("serviceimg","Serviceimg/{0}") %>' CssClass="room-image"/>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:FileUpload ID="FileUpload1" runat="server" />
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Sevice name">
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Eval("servicename") %>' Width="120px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="upsname" runat="server"  Text='<%# Eval("servicename") %>' Width="120px"></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField> 
                     
                    <asp:TemplateField HeaderText="Room Desc..">
                        <ItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Eval("servicedesc") %>' Width="500px"></asp:Label>
                        </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="upsdesc" runat="server" Text='<%# Eval("servicedesc") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                        
                    <asp:TemplateField HeaderText="Date">
                        <ItemTemplate>
                            <asp:Label ID="Label7" runat="server" Text='<%# Eval("date") %>' Width="110px"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="upsdate" TextMode="Date" runat="server" Text='<%# Eval("date") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        </div>
    </div>
</asp:Content>

